#!/bin/bash

TIME="$(date '+%H%M')"
echo "The current time is $TIME"

dbus-launch

CIVS="$(/home/azak/git/day-mode/find-twilight | cut -f1 -d\ )"
CIVE="$(/home/azak/git/day-mode/find-twilight | cut -f2 -d\ )"
echo "Daylight starts at $CIVS ends at $CIVE"
if [ $TIME -ge $CIVS ] && [ $TIME -le $CIVE ] ; then
	echo "Switching to Day mode"
	RESP=exec /home/azak/git/day-mode/day-mode
else
	echo "Switching to Night mode"
	RESP=exec /home/azak/git/day-mode/night-mode
fi

if [[ $RESP ]] ; then
	echo "Switch failure"
else
	echo "Switch sucess"
        echo "set to: $DAY_MODE"
fi
