#!/bin/bash

/usr/bin/gsettings set org.gnome.desktop.interface gtk-theme 'Flat-Plat-Light'
/usr/bin/gsettings set org.gnome.desktop.wm.preferences theme 'Flat-Plat-Light'
/usr/bin/gsettings set org.gnome.shell.extensions.user-theme name 'Flat-Plat-Light'
/usr/bin/gsettings set org.gnome.desktop.background picture-uri 'file:///home/azak/Pictures/tokyo_street_by_arsenixc.jpg'

ln -fs /home/azak/.config/terminator/config_light /home/azak/.config/terminator/config
ln -fs /home/azak/.vimrc_light /home/azak/.vimrc


