#!/bin/bash

/usr/bin/gsettings set org.gnome.shell.extensions.user-theme name 'Flat-Plat-Dark'
/usr/bin/gsettings set org.gnome.desktop.interface gtk-theme 'Flat-Plat-Dark'
/usr/bin/gsettings set org.gnome.desktop.wm.preferences theme 'Flat-Plat-Dark'
/usr/bin/gsettings set org.gnome.desktop.background picture-uri 'file:///home/azak/Pictures/tokyo_street_night_by_arsenixc.jpg'

source /home/azak/git/day-mode/check_readlink.sh  /home/azak/.vimrc /home/azak/.vimrc_dark
dbus-launch printf '1\nyes\n' | /home/azak/git/gnome-terminal-colors-solarized/install.sh -s dark --skip-dircolors
