#!/bin/bash

/usr/bin/gsettings set org.gnome.shell.extensions.user-theme name 'Flat-Plat-Dark'
/usr/bin/gsettings set org.gnome.desktop.interface gtk-theme 'Flat-Plat-Dark'
/usr/bin/gsettings set org.gnome.desktop.wm.preferences theme 'Flat-Plat-Dark'
/usr/bin/gsettings set org.gnome.desktop.background picture-uri 'file:///home/azak/Pictures/tokyo_street_night_by_arsenixc.jpg'

ln -fs /home/azak/.config/terminator/config_dark /home/azak/.config/terminator/config
ln -fs /home/azak/.vimrc_dark /home/azak/.vimrc


